<a href="https://colab.research.google.com/github/KrissSeibel/PythonBiblio/blob/lesson_1/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Тема: Numpy

Задание №1.

In [32]:
import numpy as np

In [33]:
a=np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [34]:
mean_a=a.mean(axis=0)
mean_a

array([2. , 8.4])

Задание №2.

In [35]:
a_centered=a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание №3.

In [37]:
x=a_centered[0:5, 0:1].T[0]
y=a_centered[0:5, 1:2].T[0]
a_centered_sp=x @ y
a_centered_sp

8.0

In [38]:
a_centered_sp/(a.shape[0]-1)

2.0

Задание №4.

In [39]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

#Тема: Pandas 

Задание №1.

In [54]:
import pandas as pd

In [55]:
a={'author_id': [1, 2, 3], 'author_name': ['Тургенев','Чехов','Островский']}

In [56]:
authors=pd.DataFrame(a)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [57]:
b={'author_id': [1, 1, 1, 2, 2, 3, 3], 
   'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
   'price': [450, 300, 350, 500, 450, 370, 290]}

In [58]:
book=pd.DataFrame(b)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание №2.

In [59]:
authors_price=pd.merge(authors, book, on='author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание №3.

In [60]:
top5=authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание №4.

In [67]:
author_stat1=authors_price.groupby('author_name').agg({'price': 'min'})
author_stat1=author_stat1.rename(columns={'price':'min_price'})
author_stat2=authors_price.groupby('author_name').agg({'price': 'max'})
author_stat2=author_stat2.rename(columns={'price':'max_price'})
author_stat3=authors_price.groupby('author_name').agg({'price': 'mean'})
author_stat3=author_stat3.rename(columns={'price':'mean_price'})

In [70]:
author_stat=pd.merge(author_stat1, author_stat2, on='author_name')
author_stat=pd.merge(author_stat, author_stat3, on='author_name')
author_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000